trigger:
- main

resources:
- repo: self

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'henda24/mqtt-mosquitto'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
    addPipelineData: false
    addBaseImageData: false